const teams=[
{name:'Team Alpha',slug:'team-alpha',game:'Valorant',category:'ESPORTS',captain:'Arjun',members:5,wins:18,points:2150,winRate:90,logo:'assets/team-logos/team-alpha.svg',rank:1,players:[['Arjun','Captain • Duelist'],['Rohit','IGL • Controller'],['Dev','Sentinel'],['Karan','Initiator'],['Vivek','Flex']]},
{name:'4King Esports',slug:'4king-esports',game:'BGMI',category:'ESPORTS',captain:'Rahul',members:6,wins:15,points:1890,winRate:83.3,logo:'assets/team-logos/4king-esports.svg',rank:2,players:[['Rahul','Captain • IGL'],['Aman','Assaulter'],['Vijay','Sniper'],['Karthik','Support'],['Nikhil','Entry Fragger'],['Sai','Flex']]},
{name:'Strikers FC',slug:'strikers-fc',game:'Football',category:'SPORTS',captain:'Kiran',members:11,wins:12,points:1480,winRate:75,logo:'assets/team-logos/strikers-fc.svg',rank:3,players:[['Kiran','Captain • Forward'],['Rakesh','Goalkeeper'],['Manoj','Defender'],['Surya','Midfielder'],['Ajay','Forward'],['Vamsi','Midfielder'],['Rahul','Defender'],['Tarun','Forward'],['Naveen','Defender'],['Harish','Midfielder'],['Sai','Winger']]},
{name:'Team Titans',slug:'team-titans',game:'Cricket',category:'SPORTS',captain:'Vikram',members:12,wins:10,points:1320,winRate:71.4,logo:'assets/team-logos/team-titans.svg',rank:4,players:[['Vikram','Captain • All-rounder'],['Ravi','Batsman'],['Arjun','Bowler'],['Karthik','Wicketkeeper'],['Sandeep','Batsman'],['Manish','Bowler'],['Pranav','All-rounder'],['Rohit','Batsman'],['Deepak','Bowler'],['Varun','Fielder'],['Ajay','Batsman'],['Nikhil','Bowler']]},
{name:'Red Warriors',slug:'red-warriors',game:'CS2',category:'ESPORTS',captain:'Dev',members:5,wins:9,points:1180,winRate:60,logo:'assets/team-logos/red-warriors.svg',rank:5,players:[['Dev','Captain • IGL'],['Akash','AWPer'],['Vishal','Entry'],['Rohan','Support'],['Yash','Rifler']]},
{name:'Royal Kings',slug:'royal-kings',game:'Badminton',category:'SPORTS',captain:'Sandeep',members:4,wins:8,points:1055,winRate:61.5,logo:'assets/team-logos/royal-kings.svg',rank:6,players:[['Sandeep','Captain • Singles'],['Kiran','Singles'],['Varun','Doubles'],['Aditya','Doubles']]}
];
function slugify(value){return String(value||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}
function loadCreatedTeam(requestedSlug){let created=[];try{created=JSON.parse(localStorage.getItem('kluArenaTeams')||'[]');}catch{}if(!Array.isArray(created))return null;const found=created.find(t=>slugify(t.team)===requestedSlug);if(!found)return null;const players=Array.isArray(found.members)?found.members.map((m,i)=>[m.name||`Player ${i+1}`,String(m.id)===String(found.captainId)?'Captain':`Verified Member • ${m.id}`]):[];return {name:found.team,slug:requestedSlug,game:found.game||'Competitive Game',category:String(found.category||'TEAM').toUpperCase(),captain:(found.members||[]).find(m=>String(m.id)===String(found.captainId))?.name||'Verified Captain',members:players.length,wins:0,points:0,winRate:0,logo:'assets/team-logos/custom-team.svg',rank:null,players,custom:true};}
const slug=new URLSearchParams(location.search).get('team')||'team-alpha';
const team=teams.find(t=>t.slug===slug)||loadCreatedTeam(slug)||teams[0];
const set=(id,value)=>{const el=document.getElementById(id);if(el)el.textContent=value};
set('teamName',team.name.toUpperCase());set('teamGame',`${team.game} • Captain: ${team.captain} • KLU Arena competitive squad`);set('teamCategory',`${team.category} TEAM`);set('teamRank',team.rank?`#${team.rank}`:'UNRANKED');set('matches',team.wins?Math.round(team.wins/(team.winRate/100)):0);set('wins',team.wins);set('winRate',`${team.winRate}%`);set('points',team.points);set('rankTarget',team.custom?'Play matches to enter the rankings':team.rank===1?'Defend #1':`Climb to #${Math.max(1,team.rank-1)}`);set('rankCopy',team.custom?`${team.name} is a newly created verified team. Competitive results will appear here after matches are recorded.`:(team.rank===1?`${team.name} is currently #1 in the KLU Arena leaderboard.`:`${team.name} is currently ranked #${team.rank} in the KLU Arena leaderboard.`));document.title=`${team.name} | KLU Arena`;
const logo=document.getElementById('teamLogo');if(logo){logo.src=team.logo;logo.alt=`${team.name} anime team logo`;}
const roster=document.getElementById('roster');if(roster){roster.innerHTML=team.players.map((p,i)=>`<div><span>${String(i+1).padStart(2,'0')}</span><b>${p[0]}</b><small>${p[1]}</small></div>`).join('');}
if(team.custom){const history=document.querySelector('.history');if(history)history.innerHTML='<div><span>NO MATCH HISTORY YET</span><b>NEW</b><small>Play your first tournament match to record a result.</small></div>';}
